ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: left
:toclevels: 5

= Garage

This module manages garages and character vehicles.

== Extension

=== User

[source,lua]
----
self.cdata.vehicles
self.rent_vehicles
self.vehicle_states

-- get owned vehicles
-- return map of model
User:getVehicles()

-- get vehicle model state table (may be async)
User:getVehicleState(model)
----

=== Server

[source,lua]
----
self.cfg
self.models -- map of all garage defined models

-- get vehicle trunk chest id by character id and model
Garage.getVehicleChestId(cid, model)
----

=== Client

[source,lua]
----
self.vehicles -- map of vehicle model => veh id (owned vehicles)
self.hash_models -- map of hash => model

-- veh: vehicle game id
-- return owner character id and model or nil if not managed by vRP
Garage:getVehicleInfo(veh)

-- return true if spawned (if not already out)
Garage:spawnVehicle(model, pos) -- one vehicle per model allowed at the same time

-- return true if despawned
Garage:despawnVehicle(model)

-- return map of veh => distance
Garage:getNearestVehicles(radius)

-- return veh
Garage:getNearestVehicle(radius)

-- try to re-own the nearest vehicle
Garage:tryOwnNearestVehicle(radius)

Garage:fixNearestVehicle(radius)

Garage:replaceNearestVehicle(radius)

-- return model or nil
Garage:getNearestOwnedVehicle(radius)

-- return ok,x,y,z
Garage:getAnyOwnedVehiclePosition()

-- return x,y,z or nil
Garage:getOwnedVehiclePosition(model)

-- eject the ped from the vehicle
Garage:ejectVehicle()

Garage:isInVehicle()

-- return model or nil if not in owned vehicle
Garage:getInOwnedVehicleModel()

-- VEHICLE COMMANDS

Garage:vc_openDoor(model, door_index)

Garage:vc_closeDoor(model, door_index)

Garage:vc_detachTrailer(model)

Garage:vc_detachTowTruck(model)

Garage:vc_detachCargobob(model)

Garage:vc_toggleEngine(model)

-- return true if locked, false if unlocked
Garage:vc_toggleLock(model)

-- TUNNEL

Garage.tunnel.spawnVehicle = Garage.spawnVehicle
Garage.tunnel.despawnVehicle = Garage.despawnVehicle
Garage.tunnel.fixNearestVehicle = Garage.fixNearestVehicle
Garage.tunnel.replaceNearestVehicle = Garage.replaceNearestVehicle
Garage.tunnel.getNearestOwnedVehicle = Garage.getNearestOwnedVehicle
Garage.tunnel.getAnyOwnedVehiclePosition = Garage.getAnyOwnedVehiclePosition
Garage.tunnel.getOwnedVehiclePosition = Garage.getOwnedVehiclePosition
Garage.tunnel.getInOwnedVehicleModel = Garage.getInOwnedVehicleModel
Garage.tunnel.ejectVehicle = Garage.ejectVehicle
Garage.tunnel.isInVehicle = Garage.isInVehicle
Garage.tunnel.vc_openDoor = Garage.vc_openDoor
Garage.tunnel.vc_closeDoor = Garage.vc_closeDoor
Garage.tunnel.vc_detachTrailer = Garage.vc_detachTrailer
Garage.tunnel.vc_detachTowTruck = Garage.vc_detachTowTruck
Garage.tunnel.vc_detachCargobob = Garage.vc_detachCargobob
Garage.tunnel.vc_toggleEngine = Garage.vc_toggleEngine
Garage.tunnel.vc_toggleLock = Garage.vc_toggleLock
----

.Events
[horizontal]
`garageVehicleSpawn(model)`:: called when a vehicle is spawned from a garage
`garageVehicleStore(model)`:: called when a vehicle is stored into a garage

== Item

=== repairkit

Used to repair vehicles, but can be used for other stuff.

== Menu

=== vehicle

Owned vehicle menu.

.data
[horizontal]
model:: vehicle model

=== garage

Garage menu.

.data
[horizontal]
type:: garage type
vehicles:: garage type table

=== garage.owned

Garage sub-menu.
Same data as `garage`.

=== garage.buy

Garage sub-menu.
Same data as `garage`.

=== garage.sell

Garage sub-menu.
Same data as `garage`.

=== garage.rent

Garage sub-menu.
Same data as `garage`.

== Permission

=== in_vehicle

`!in_vehicle`

Will do a tunnel call.

=== in_owned_vehicle

`!in_owned_vehicle[.<model>]`

Will do a tunnel call.

[horizontal]
model:: (optional) vehicle model

.Examples
[horizontal]
`!in_owned_vehicle`:: check if inside an owned vehicle
`!in_owned_vehicle.taxi`:: check if inside owned taxi model
