ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: left
:toclevels: 5

= home_components

This module adds some home components.

== Extension

=== Server

[source,lua]
----
self.cfg
----

== Menu

=== home:component:wardrobe

Wardrobe menu.

.data
[horizontal]
sets:: map of name => customization

=== home:component:gametable

Gametable menu.

=== home:component:radio

Radio menu.

.data
[horizontal]
component:: radio component

== Home component

=== chest

A home chest to store items. The chest is bound to the character, not to the home or the component.

.config
[horizontal]
weight:: (optional) chest max weight, 200 by default

=== wardrobe

Wardrobe to save/restore clothes.

=== gametable

Gametable to play simple games with other people (bet...).

=== transformer

Transformer component.

.config
[horizontal]
cfg:: transformer config
map_entity:: (optional) map entity at the component position

=== radio

Component to play music in the home.

.config
[horizontal]
stations:: map of name => audio source URL
