ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: left
:toclevels: 5

= Documentation

== Guidelines

vRP is a framework, its goal is to provide a set of tools and flexibility.

It implies that you should never modify the core files of vRP, only the files in the `cfg` folder. 

[CAUTION]
====
By modifiying the core files of vRP, you are not using the framework, instead you are creating a fork of vRP, which is not vRP anymore. Forks should be new maintained projects, not modifications from a single user. 

Doing this fragments the vRP community, so vRP extensions are not guaranteed to work with everyone, causing a lot of issues. It also wastes your time by manually updating vRP or prevents you from doing it at all.

Instead, vRP should be improved to be flexible as possible to suit your needs by making a **Feature request**, then developers can properly extend vRP by creating extensions without modifying core files, and everyone can use it.
====

A framework code should not be customized by definition, because a framework is used to build a custom experience by using the availables features. There is no point in saying "`You should create your custom framework.`", unless it doesn't fit your needs at all.

== Deployment

=== Installation

Clone the repository or download the master https://github.com/ImagicTheCat/vRP/archive/master.zip[archive] and copy the `vrp` directory to your resource folder. Add `vrp` to the loading resource list (first after the basic FiveM resources is better).

=== Configuration

WARNING: Only the files in the `cfg/` directory should be modified. 

There is one required file to configure before launching the server, `cfg/base.lua`, to setup the MySQL database credentials, but it also depends on the DB driver used.

There is a lot to configure in vRP base, everyone can make his unique server. +
Everything you need to know is in the configuration files, default stuff is here as an example.

==== Database

To run vRP, you need to also install a DB driver, it's a resource/extension used to communicate with a MySQL database. 

NOTE: Some maintained DB drivers: https://github.com/ImagicTheCat/vRP-db-drivers +
`ghmattimysql` bridge is recommended.

=== Update

.A good way to update (bleeding-edge):
. use git to clone vRP to create your own version of it, checkout the branch you want, create a branch from it
. create a symbolic link (or an update script) to `vrp/` in your fxserver resources directory
. (repeat) configure, commit your changes, stay updated with the vRP repository, solve conflicts

This way, you will know when config files should be updated and what exactly has been updated.

.A more primitive way to update:
. save your `cfg/` folder somewhere
. copy all new files in `vrp/`
. compare your old `cfg/` folder with the new one, fill the gaps (one mistake will break everything, take your time)
. replace the new `cfg/` folder with the old modified `cfg/` folder

=== Issues / Features / Help

WARNING: The issue section is only for bug reports and feature requests. I will close (and ban) issues not related to the core of vRP, to keep the github clean.
Don't submit issues about vRP modifications, they will be closed without warning.

When submitting an issue, add any information you can find, with all details. Saying that something doesn't work is useless and will not solve the issue.
If you have errors in your console BEFORE the issue happen, everything could be corrupted, so the issue is irrelevant, you should solve all unrelated errors before submitting issues.

NOTE: For questions, help, discussions around the project, please go instead on the vRP thread of the FiveM forum here: https://forum.fivem.net/t/release-vrp-framework/22894

== Developers

See the developers link:dev/[documentation].
